
package cm4108.cw.Subscription.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName="Subscription")
public class Subscription{

private String subscriptionID;
private String name;
private String subname;


public Subscription(){} //end method

public Subscription(String name, String subname){
this.setName(name);
this.setSubname(subname);
} //end method

//set table attributes

@DynamoDBHashKey(attributeName="subscriptionID")
@DynamoDBAutoGeneratedKey
public String getSubscriptionID(){
	return subscriptionID;
} 
public void setSubscriptionID(String subscriptionID){
	this.name = subscriptionID;
}


@DynamoDBAttribute(attributeName="name")
public String getName(){
	return name;
} 
public void setName(String name){
	this.name = name;
} 


@DynamoDBAttribute(attributeName="subname")
public String getSubname(){
	return subname;
} 
public void setSubname(String subname) {
	this.subname = subname;
}

}//end class
